spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
      authentication-database: admin
      database: ${MONGO_DB_NAME}

  servlet:
    context-path: /api

server:
  port: 8080
